FROM ghcr.io/home-assistant/base:latest

ARG BUILD_VERSION=0.0.1
ARG BUILD_ARCH=amd64

LABEL \
  io.hass.version="${BUILD_VERSION}" \
  io.hass.type="addon" \
  io.hass.arch="${BUILD_ARCH}"

CMD [ "sh", "-c", "echo 'Placeholder add-on only. Replace this folder before production use.'" ]
